# Generated by Django 4.2.7 on 2023-12-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='user',
            new_name='session_key',
        ),
    ]
